// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC79eZGsN48hx-39dtL4o13hEycMIZJZi4',
    appId: '1:693111511379:web:2e304220a13f97a033e9a6',
    messagingSenderId: '693111511379',
    projectId: 'todo-app-82a32',
    authDomain: 'todo-app-82a32.firebaseapp.com',
    storageBucket: 'todo-app-82a32.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeFhT1zRjh-zIPosJUVPZ7r35aMcm3IJA',
    appId: '1:693111511379:android:380270ac3e1d918833e9a6',
    messagingSenderId: '693111511379',
    projectId: 'todo-app-82a32',
    storageBucket: 'todo-app-82a32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXNvKJJMsPQyqMqL1aER4xCa66tafkbTI',
    appId: '1:693111511379:ios:449a686c5d63f60733e9a6',
    messagingSenderId: '693111511379',
    projectId: 'todo-app-82a32',
    storageBucket: 'todo-app-82a32.firebasestorage.app',
    iosBundleId: 'com.example.todofire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXNvKJJMsPQyqMqL1aER4xCa66tafkbTI',
    appId: '1:693111511379:ios:449a686c5d63f60733e9a6',
    messagingSenderId: '693111511379',
    projectId: 'todo-app-82a32',
    storageBucket: 'todo-app-82a32.firebasestorage.app',
    iosBundleId: 'com.example.todofire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC79eZGsN48hx-39dtL4o13hEycMIZJZi4',
    appId: '1:693111511379:web:3e5a8d2f2df2872033e9a6',
    messagingSenderId: '693111511379',
    projectId: 'todo-app-82a32',
    authDomain: 'todo-app-82a32.firebaseapp.com',
    storageBucket: 'todo-app-82a32.firebasestorage.app',
  );
}
